version: "3.3"
services:
  main-api:
    build:
      docker:
        - image: urvi99/user
          environment:
            FLASK_CONFIG: testing
      steps:
        - checkout
        - run:
            name: Setup VirtualEnv
            command: |
              echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
              echo 'export IMAGE_NAME=user' >> $BASH_ENV 
              virtualenv venv
              . venv/bin/activate
              pip install --no-cache-dir -r requirements.txt
        - run:
            name: Run Tests
            command: |
              . venv/bin/activate
              python test.py
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: Build and push Docker image
            command: |
              . venv/bin/activate
              pyinstaller -F run.py
              docker build -t urvi99/$IMAGE_NAME:$TAG .
